services:
  appflyte-web-servic-test-78:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appflyte-web-servic-test-78
    ports:
      - "3007:3000"
    env_file:
      - .env
    networks:
      - appflyte

networks:
  appflyte:
      external: true